### ISSUE TITLE
What if top-level is a list?

### ISSUE THREAD

**Issue by matthiasbeyer** [quitoque/hdlbr#2]
Hi,

in my case, my JSON file looks like this:

```json
[ {"some":"data"}, {"some":"more"} ]
```

So I have a List as top-level element. I guess your tool does not handle this case.

**Comment by matthiasbeyer** [comment]
Rel: https://github.com/sunng87/handlebars-rust/issues/261

**Comment by matthiasbeyer** [comment]
TIL:

```
#each . as |t|
```

**Comment by jerome-arzel** [comment]
Is your issue solved?

**Comment by matthiasbeyer** [comment]
Yes, thanks.
